### ISSUE TITLE
Crash when spawning mobs.

### ISSUE THREAD

**Issue by Mewtwoy** [mcNETDev/modularmobfarms#1]
Description: Ticking block entity

java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Unknown Source)
    at de.dwcode.mmfarms.blocks.SimpleControllerTile.getRandomLoot(SimpleControllerTile.java:153)
    at de.dwcode.mmfarms.blocks.SimpleControllerTile.update(SimpleControllerTile.java:178)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zbj000(World.java:4137)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

Additional note: Tons of experience & loot spawn on the sky after the multiblock is configured, no power.

**Comment by mcNETDev** [comment]
Thank you, I'll have a look in it tomorrow.
Are the experience and items really falling from the sky?
It is normal for mobs to be spawned in the sky to register the loot, but none of it should come down.
What other mods did you install with?

**Comment by Mewtwoy** [comment]
Other mods: SolarGeneration (Power source), optifine & lostcities.

**Comment by Zebralear** [comment]
I got a crash like this one when the farm tried to kill Wither bosses.
